services:
  - type: web
    name: libass-backend
    env: python
    plan: free
    region: ohio
    rootDir: drape
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PORT
        value: 10000
