services:
  - type: web
    name: libass-backend
    env: docker
    plan: free
    region: ohio
    # Render uses the Dockerfile present in this directory automatically
    envVars:
      - key: PORT
        value: 10000 # Render often defaults to 10000 for Docker
